ProyectoGAE4Galactic1/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include
from core.views import ProductListView
from. import views

urlpatterns = [
    path('',views.IndexInicio, name='Inicio'),
    path('Productos',ProductListView.as_view(), name='index'),
    path('admin/', admin.site.urls),
#login/register
    path('usuarios/login', views.login_view, name='login'),
    path('usuarios/logout', views.logout_view, name='logout'),
    path('usuarios/register', views.register_view, name='register'),
#PQRS
    path('PQRS', views.PQRSC_view, name='PQRScliente'),
    path('PQRS/PQRSConsulta', views.PQRSConsultar_view, name='PQRSConsulta'),
    path('PQRS/PQRSActualizar/<int:pk>/', views.PQRSActualizar_view, name='PQRSActualizar'),
    path('PQRS/PQRSEliminar/<int:pk>/', views.eliminar_pqrs, name='PQRSEliminar'),
    path('respuesta_pqrs/<int:respuesta_id>/', views.ver_respuesta, name='ver_respuesta'),
#Contacto y Acerca de
    path('Contactenos', views.Contacto_view, name='Contactenos'),
    path('Acerca', views.Acerca_view, name='AcercaDe'),

#Productview
    path ('productos/', include('core.urls')),
    
    path('carrito/', include('carts.urls')),
    path('orden/', include('orders.urls')),
    path('direcciones/', include('shipping_addresses.urls')),
    path('pagos/', include('billing_profiles.urls')),




]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    
    
    

carts/urls.py
from django.urls import path

from . import views


app_name = 'carts'

urlpatterns =[
    path('', views.cart, name='cart'),
    path('agregar', views.add, name='add'),
    path('eliminar', views.remove, name='remove')
]

core/urls.py
from django.urls import path

from . import views

urlpatterns = [
    
    path ('search', views.ProductSearchListView.as_view(), name='search'),
    path ('<slug:slug>',views.ProductDetailView.as_view(), name='product')
]

orders/urls.py
from django.urls import path

from . import views

app_name = 'orders'

urlpatterns = [
    path('', views.order, name='order'),
    path('direccion', views.address, name='address')
]

carts/models.py
import uuid
import decimal
from django.db import models

from Usuarios.models import User
from core.models import Producto

from django.db.models.signals import pre_save
from django.db.models.signals import m2m_changed
from django.db.models.signals import post_save



class Cart(models.Model):
    cart_id = models.CharField(max_length=100,  null=False, blank=False, unique=True)
    user = models.ForeignKey(User, null=True, blank=True, on_delete=models.CASCADE)
    Productos = models.ManyToManyField(Producto, through='CartProducts')
    subtotal = models.DecimalField(default=0.0, max_digits=8, decimal_places=2)
    total = models.DecimalField(default=0.0, max_digits=8, decimal_places=2)
    created_at = models.DateTimeField(auto_now_add=True)
    
    FEE = 0.05
    
    def __str__(self):
        return self.cart_id
    
    def update_totals(self):
        self.update_subtotal()
        self.update_total()

        if self.order:
            self.order.update_total()


        
    def update_subtotal(self):
        self.subtotal = sum([
            cp.quantity * cp.Producto.PrecioProducto for cp in self.products_related() 
                             
        ])
        self.save()    
        
    def update_total(self):
        self.total = self.subtotal + (self.subtotal * decimal.Decimal(Cart.FEE) )
        self.save()
        
    
    def products_related(self):
        return self.cartproducts_set.select_related('Producto')
    
    
    @property
    def order(self):
        return self.order_set.first()
    



class CartProducts(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    Producto = models.ForeignKey(Producto, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    created_at = models.DateTimeField(auto_now_add=True)
    

def set_cart_id(sender, instance, *args, **kwargs):
    if not instance.cart_id:
        instance.cart_id = str(uuid.uuid4())

def update_totals(sender, instance, action, *args, **kwargs):
    if action == 'post_add' or action == 'post_remove' or action == 'post_clear':
        instance.update_totals()
        

def post_save_update_totals(sender, instance, *args, **akwargs):
    instance.cart.update_totals()


pre_save.connect(set_cart_id, sender=Cart)
post_save.connect(post_save_update_totals, sender=CartProducts)
m2m_changed.connect(update_totals, sender=Cart.Productos.through)

carts/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from django.shortcuts import get_list_or_404
from django.shortcuts import get_object_or_404
from .models import CartProducts
from .models import Cart
from core.models import Producto
from .utils import get_or_create_cart
from .models import CartProducts


def cart(request):
    cart = get_or_create_cart(request)
        
    
    return render(request, 'carts/cart.html', {
        'cart': cart
    })
    
def add(request):
    cart = get_or_create_cart(request)
    producto = Producto.objects.get(pk=request.POST.get('producto_id'))
    quantity = request.POST.get('quantity', 1)
    
    cart.Productos.add(producto, through_defaults={
      'quantity': quantity
    })
    
    #cart_product = CartProducts.objects.create(cart=cart, producto=producto, quantity=quantity)
    
    return render(request, 'carts/add.html', {
        'producto': producto
    })
    
def remove(request):
    if request.method == 'POST':
        cart_product_id = request.POST.get('cart_product_id')
        if cart_product_id:
            try:
                cart_product = get_object_or_404(CartProducts, id=cart_product_id)
                cart = cart_product.cart  # Obtenemos el carrito al que pertenece el producto
                
                # Eliminamos el producto del carrito
                cart_product.delete()
                
                # Actualizamos el subtotal y el total del carrito
                cart.update_totals()
                
            except CartProducts.DoesNotExist:
                # Manejar el caso en que el producto no existe
                pass
    return redirect('carts:cart')

carts/templates/carts/add.html
{% extends 'base.html' %}
{% load product_extras %}

{% block content %}
<div class="container bg-white rounded p-4 mt-5">
    <div class="row">
        <div class="col-md-6 text-center">
            {% if producto.image %}
            <img src="{{ producto.image.url }}" alt="Imagen del Producto" class="img-fluid mb-3" style="max-height: 300px;">
            {% endif %}
        </div>
        <div class="col-md-6">
            <div class="h3 font-weight-bold text-success mb-4">
                Producto agregado al carrito de compras
            </div>
            <div class="mb-3">
                <a href="#" class="text-decoration-none text-dark">
                    <h4>{{ producto.nombre_producto }}</h4>
                </a>
            </div>
            <div class="font-weight-bold text-danger mb-3">
                Precio: {{ producto.PrecioProducto | price_format }}
            </div>
            <div class="mt-4">
                <a href="{% url 'carts:cart' %}" class="btn btn-info mr-3" style="color: #fff;" >Ver Carrito</a>
                <a href="{% url 'index' %}" class="btn btn-outline-primary">Seguir Comprando</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

carts/templates/carts/cart.html
{% extends 'base.html' %}
{% load product_extras %}

{% block content %}
    <div class="container mt-4">
        {% if cart.Productos.exists %}
        <div class="row">
            <div class="col-lg-8">
                <div class="table-responsive">
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th scope="col">Imagen</th>
                                <th scope="col">Nombre</th>
                                <th scope="col">Cantidad</th>
                                <th scope="col">Precio</th>
                                <th scope="col">Eliminar</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for cp in cart.products_related %}
                            {% with Producto=cp.Producto %}
                            <tr>
                                <td>
                                    {% if Producto.image %}
                                    <img src="{{ Producto.image.url }}" alt="Imagen del producto" class="img-thumbnail" style="max-width: 100px;">
                                    {% endif %}
                                </td>
                                <td>{{ Producto.nombre_producto }}</td>
                                <td>{{ cp.quantity }}</td>
                                <td>{{ Producto.PrecioProducto | price_format }}</td>
                                <td>
                                    {% include 'carts/snippets/remove.html' %}
                                </td>
                            </tr>
                            {% endwith %}
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
            
            <div class="col-lg-4"> 
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Resumen del Pedido</h5>
                        <hr>
                        <div class="font-weight-bold mb-3">
                            Subtotal ({{ cart.Productos.count }} productos): <span class="text-danger">{{ cart.subtotal | price_format }}</span>
                        </div>
                        <a href="{% url 'orders:order'%}" class="btn btn-info mr-3" style="color: #fff;" >Proceder al pago</a>

                        <a href="{% url 'index' %}" class="btn btn-secondary btn-block mt-2">Seguir comprando</a>
                    </div>
                </div>
            </div>
        </div>
        {% else %}
        <div class="row justify-content-center">
            <div class="col-lg-6">
                <div class="alert alert-info text-center" role="alert">
                    Tu carrito de compras está vacío.
                </div>
            </div>
        </div>
        {% endif %}
    </div>
{% endblock %}