ProyectoGAE4Galactic1/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include
from core.views import ProductListView
from. import views

urlpatterns = [
    path('',views.IndexInicio, name='Inicio'),
    path('Productos',ProductListView.as_view(), name='index'),
    path('admin/', admin.site.urls),
#login/register
    path('usuarios/login', views.login_view, name='login'),
    path('usuarios/logout', views.logout_view, name='logout'),
    path('usuarios/register', views.register_view, name='register'),
#PQRS
    path('PQRS', views.PQRSC_view, name='PQRScliente'),
    path('PQRS/PQRSConsulta', views.PQRSConsultar_view, name='PQRSConsulta'),
    path('PQRS/PQRSActualizar/<int:pk>/', views.PQRSActualizar_view, name='PQRSActualizar'),
    path('PQRS/PQRSEliminar/<int:pk>/', views.eliminar_pqrs, name='PQRSEliminar'),
    path('respuesta_pqrs/<int:respuesta_id>/', views.ver_respuesta, name='ver_respuesta'),
#Contacto y Acerca de
    path('Contactenos', views.Contacto_view, name='Contactenos'),
    path('Acerca', views.Acerca_view, name='AcercaDe'),

#Productview
    path ('productos/', include('core.urls')),
    
    path('carrito/', include('carts.urls')),
    path('orden/', include('orders.urls')),
    path('direcciones/', include('shipping_addresses.urls')),
    path('pagos/', include('billing_profiles.urls')),




]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    
    
    

core/urls.py
from django.urls import path

from . import views

urlpatterns = [
    
    path ('search', views.ProductSearchListView.as_view(), name='search'),
    path ('<slug:slug>',views.ProductDetailView.as_view(), name='product')
]

orders/urls.py
from django.urls import path

from . import views

app_name = 'orders'

urlpatterns = [
    path('', views.order, name='order'),
    path('direccion', views.address, name='address')
]

orders/models.py
import uuid
from enum import Enum
from django.db import models
from Usuarios.models import User
from carts.models import Cart 
from shipping_addresses.models import ShippingAddress

from django.db.models.signals import pre_save

class OrderStatus(Enum):
    CREATED = 'CREATED'
    PAYED = 'PAYED'
    COMPLETED = 'COMPLETED'
    CANCELED = 'CANCELED'


choices = [ (tag, tag.value) for tag in OrderStatus ]

class Order(models.Model):
    order_id = models.CharField(max_length=100, null=False, blank=False, unique=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    status = models.CharField(max_length=50, choices=choices, 
                                default=OrderStatus.CREATED) #Enum
    shipping_total = models.DecimalField(default=5, max_digits=8, decimal_places=2)
    total = models.DecimalField(default=0, max_digits=8, decimal_places=2)
    created_at = models.DateTimeField(auto_now_add=True)
    shipping_address = models.ForeignKey(ShippingAddress,
                                        null=True, blank=True, 
                                        on_delete=models.CASCADE)

    def __str__(self):
        return self.order_id
    
    def get_or_set_shipping_address(self):
        if self.shipping_address:
            return self.shipping_address
        
        shipping_address = self.user.shipping_address
        if shipping_address:
            self.update_shipping_address(shipping_address)

        return shipping_address
    
    def update_shipping_address(self, shipping_address):
        self.shipping_address = shipping_address
        self.save()

    def update_total(self):
        self.total = self.get_total()
        self.save()

    def get_total(self):
        return self.cart.total + self.shipping_total  

def set_order_id(sender, instance, *args, **kwargs):
    if not instance.order_id:
        instance.order_id = str(uuid.uuid4())


def set_total(sender, instance, *args, **kwargs):
    instance.total = instance.get_total()

pre_save.connect(set_order_id, sender=Order)
pre_save.connect(set_total, sender=Order)

orders/views.py
from django.shortcuts import render

from .utils import breadcrumb
from .utils import get_or_create_order
from carts.utils import get_or_create_cart

from .models import Order




def order(request):
    cart = get_or_create_cart(request)
    order = get_or_create_order(cart, request)


    return render(request, 'orders/order.html', {
        'cart': cart,
        'order' : order,
        'breadcrumb' : breadcrumb()
    })

def address(request):
    cart = get_or_create_cart(request)
    order = get_or_create_order(cart, request)

    shipping_address = order.get_or_set_shipping_address()

    return render(request, 'orders/address.html',{
        'cart' : cart,
        'order' : order,
        'shipping_address' : shipping_address,
        'breadcrumb' : breadcrumb(address=True)
    })

orders/templates/orders/snippets/breadcrumb.html
<div class="mt-2">

      <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            {% for item in breadcrumb %}
                {% if item.active %}
                    <a class="breadcrumb-item" href="{{ item.url }}">{{ item.title }}</a>
                {% else %}
                    <span class="breadcrumb-item active">{{ item.title }}</span>
                {% endif%}
            {% endfor %}

        </ol>
      </nav>

orders/templates/orders/snippets/factura.html
{% load product_extras %}
<div class="col-sm-6">
    <div class="card">

        <div class="card-body">
            <h5 class="card-title"><h3>Compra realizada exitosamente<h3></h5>



            <table class="table table-borderless table-sm">
                <thead>
                    <tr>
                        <th scope="col"></th>
                        <th scope="col"></th>
                    </tr>
                
                </thead>
                <tbody>
                    <tr>
                        <td>Productos:</td>
                        <td>{{ cart.total | price_format }}</td>
                    </tr>
                    <tr>
                       <td>Envío:</td> 
                       <td>{{ order.shipping_total | price_format }}</td> 
                    </tr>
                </tbody>
     </div>
     <div class="">
        <hr>
        <div class="font-weight-bold text-danger">
            Total (impuestos incluidos)
            <div class"d-inline-block">
                {{ order.total | price_format }}
            
            </div>
        </div>

     </div>
    </div>
</div>

orders/templates/orders/snippets/product.html
{% load product_extras %}

 <div class="row mt-4">
        <div class="col-2">
            {% if producto.image %}
            <img src="{{ producto.image.url }}" alt="Imagen del producto" class="img-fluid">
            {% endif %}
        </div>
        <div class="col-5">
            <div class="row">
            <strong>
                <a href={% url 'product' producto.slug%}>"{{ producto.nombre_producto }}"<a/>
            </strong>
        </div>
        <div class="row">
            <strong class="text-danger">Precio: {{ producto.PrecioProducto | price_format }}</strong>
    </div>
</div>
</div>

orders/templates/orders/snippets/resume.html
{% load product_extras %}
<div class="col-sm-6">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="card row justify-content-center">
                    <div class="card-body">
                        <h5 class="card-title">Resumen del pedido</h5>
                        <table class="table table-borderless table-sm">
                            <thead>
                                <tr>
                                    <th scope="col"></th>
                                    <th scope="col"></th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td>Productos:</td>
                                    <td>{{ cart.total | price_format }}</td>
                                </tr>
                                <tr>
                                    <td>Envío:</td> 
                                    <td>{{ order.shipping_total | price_format }}</td> 
                                </tr>
                            </tbody>
                        </table>
                        <hr>
                        <div class="font-weight-bold text-danger">
                            Total (impuestos incluidos)
                            <div class="d-inline-block">
                                {{ order.total | price_format }}
                            </div>
                        </div>
                        <div class="mt-2">
                            <a href="{% url 'orders:address' %}" class="btn btn-warning">Confirmar pedido</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    
</div>